[package]
name = "defining-files-neatly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "defining-files-neatly"
path = "defining-files-neatly.rs"
