[package]
name = "bufreader-lines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "bufreader-lines"
path = "bufreader-lines.rs"
