[package]
name = "not-quite-file-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "not-quite-file-1"
path = "not-quite-file-1.rs"
