[package]
name = "simple-with-linenums"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "simple-with-linenums"
path = "simple-with-linenums.rs"
