[package]
name = "add-with-lifetimes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "add-with-lifetimes"
path = "add-with-lifetimes.rs"
