[package]
name = "check-sats-3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "check-sats-3"
path = "check-sats-3.rs"
